# This is a placeholder for your actual hardware-configuration.nix
# Please replace this file with the one generated by:
# nixos-generate-config --show-config
# or copy it from /etc/nixos/hardware-configuration.nix

{ config, lib, pkgs, modulesPath, ... }:

{
  # Minimal placeholder to allow evaluation
  fileSystems."/" = { device = "/dev/null"; };
  boot.loader.grub.device = "/dev/null";
}
